interface Feedback {
  id: string;
  interviewId: string;
  totalScore: number;
  categoryScores: Array<{
    name: string;
    score: number;
    comment: string;
  }>;
  strengths: string[];
  areasForImprovement: string[];
  finalAssessment: string;
  createdAt: string;
}

interface Conversation {
  id: string; // Auto-generated by Firebase
  topic: string; // e.g. "personal", "food", "work"
  difficulty: string; // "beginner" | "intermediate"
  context: string; // e.g. "daily life", "work", "shopping"
  focus: string; // "vocabulary" | "fluency" | "pronunciation"
  starters: string[]; // Conversation prompts/questions
  createdAt: string; // ISO timestamp
  finalized: boolean; // Always true for generated conversations
}

interface CreateFeedbackParams {
  conversationId: string;
  userId: string;
  transcript: { role: string; content: string }[];
  feedbackId?: string;
}
interface CreateConversationFeedbackParams {
  conversationId: string;
  userId: string;
  transcript: { role: string; content: string }[];
  feedbackId?: string;
}

interface User {
  name: string;
  email: string;
  id: string;
}

interface ConversationCardProps {
  conversationId?: string;
  userId?: string;
  topic: string;
  difficulty: string;
  context: string;
  createdAt?: string;
  starters?: string[]; // For preview purposes
}

interface AgentProps {
  userName: string;
  userId?: string;
  interviewId?: string;
  feedbackId?: string;
  type: "generate" | "conversation";
  questions?: string[];
}

interface ConversationAgentProps {
  userName: string;
  userId?: string;
  conversationId?: string;
  feedbackId?: string;
  type: "generate" | "conversation";

  // for the voice agent context
  topic?: string;
  difficulty?: string;
  context?: string;
  focus?: string;
  starters?: string[];
}

interface RouteParams {
  params: Promise<Record<string, string>>;
  searchParams: Promise<Record<string, string>>;
}

interface GetFeedbackByConversationIdParams {
  conversationId: string;
  userId: string;
}

interface GetLatestConversationsParams {
  userId: string;
  limit?: number;
}

interface SignInParams {
  email: string;
  idToken: string;
}

interface SignUpParams {
  uid: string;
  name: string;
  email: string;
  password: string;
}

type FormType = "sign-in" | "sign-up";
